// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MumbleUDP.proto
// Protobuf Java Version: 4.35.1

package se.lublin.humla.protobuf;

@com.google.protobuf.Generated
public final class MumbleUDP {
  private MumbleUDP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AudioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MumbleUDP.Audio)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
     * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
     * and all other targets are understood as shout/whisper targets that have previously been registered via a
     * VoiceTarget message (via TCP).
     * </pre>
     *
     * <code>uint32 target = 1;</code>
     * @return Whether the target field is set.
     */
    boolean hasTarget();
    /**
     * <pre>
     * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
     * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
     * and all other targets are understood as shout/whisper targets that have previously been registered via a
     * VoiceTarget message (via TCP).
     * </pre>
     *
     * <code>uint32 target = 1;</code>
     * @return The target.
     */
    int getTarget();

    /**
     * <pre>
     * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
     * 0: Normal speech
     * 1: Shout to channel
     * 2: Whisper to user
     * 3: Received via channel listener
     * </pre>
     *
     * <code>uint32 context = 2;</code>
     * @return Whether the context field is set.
     */
    boolean hasContext();
    /**
     * <pre>
     * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
     * 0: Normal speech
     * 1: Shout to channel
     * 2: Whisper to user
     * 3: Received via channel listener
     * </pre>
     *
     * <code>uint32 context = 2;</code>
     * @return The context.
     */
    int getContext();

    /**
     * <pre>
     * The session of the client (sender) this audio was originally sent from. This field is not required when sending
     * audio to the server, but will always be set when receiving audio from the server.
     * </pre>
     *
     * <code>uint32 sender_session = 3;</code>
     * @return The senderSession.
     */
    int getSenderSession();

    /**
     * <pre>
     * The number of the first contained audio frame (indicating the position of that frame in the overall audio stream)
     * </pre>
     *
     * <code>uint64 frame_number = 4;</code>
     * @return The frameNumber.
     */
    long getFrameNumber();

    /**
     * <pre>
     * The actual voice data payload in the Opus format.
     * </pre>
     *
     * <code>bytes opus_data = 5;</code>
     * @return The opusData.
     */
    com.google.protobuf.ByteString getOpusData();

    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @return A list containing the positionalData.
     */
    java.util.List<java.lang.Float> getPositionalDataList();
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @return The count of positionalData.
     */
    int getPositionalDataCount();
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @param index The index of the element to return.
     * @return The positionalData at the given index.
     */
    float getPositionalData(int index);

    /**
     * <pre>
     * A volume adjustment determined by the server for this audio packet. It is up to the client to apply this adjustment to
     * the resulting audio (or not). Note: A value of 0 means that this field is unset.
     * </pre>
     *
     * <code>float volume_adjustment = 7;</code>
     * @return The volumeAdjustment.
     */
    float getVolumeAdjustment();

    /**
     * <pre>
     * A flag indicating whether this audio packet represents the end of transmission for the current audio stream
     * </pre>
     *
     * <code>bool is_terminator = 16;</code>
     * @return The isTerminator.
     */
    boolean getIsTerminator();

    public se.lublin.humla.protobuf.MumbleUDP.Audio.HeaderCase getHeaderCase();
  }
  /**
   * Protobuf type {@code MumbleUDP.Audio}
   */
  public  static final class Audio extends
      com.google.protobuf.GeneratedMessageLite<
          Audio, Audio.Builder> implements
      // @@protoc_insertion_point(message_implements:MumbleUDP.Audio)
      AudioOrBuilder {
    private Audio() {
      opusData_ = com.google.protobuf.ByteString.EMPTY;
      positionalData_ = emptyFloatList();
    }
    private int headerCase_ = 0;
    private java.lang.Object header_;
    public enum HeaderCase
        implements com.google.protobuf.AbstractMessageLite.InternalOneOfEnum {
      TARGET(1),
      CONTEXT(2),
      HEADER_NOT_SET(0);
      private final int value;
      private HeaderCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static HeaderCase valueOf(int value) {
        return forNumber(value);
      }

      public static HeaderCase forNumber(int value) {
        switch (value) {
          case 1: return TARGET;
          case 2: return CONTEXT;
          case 0: return HEADER_NOT_SET;
          default: return null;
        }
      }
      @java.lang.Override public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public HeaderCase
    getHeaderCase() {
      return HeaderCase.forNumber(
          headerCase_);
    }

    private void clearHeader() {
      headerCase_ = 0;
      header_ = null;
    }

    public static final int TARGET_FIELD_NUMBER = 1;
    /**
     * <pre>
     * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
     * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
     * and all other targets are understood as shout/whisper targets that have previously been registered via a
     * VoiceTarget message (via TCP).
     * </pre>
     *
     * <code>uint32 target = 1;</code>
     * @return Whether the target field is set.
     */
    @java.lang.Override
    public boolean hasTarget() {
      return headerCase_ == 1;
    }
    /**
     * <pre>
     * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
     * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
     * and all other targets are understood as shout/whisper targets that have previously been registered via a
     * VoiceTarget message (via TCP).
     * </pre>
     *
     * <code>uint32 target = 1;</code>
     * @return The target.
     */
    @java.lang.Override
    public int getTarget() {
      if (headerCase_ == 1) {
        return (java.lang.Integer) header_;
      }
      return 0;
    }
    /**
     * <pre>
     * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
     * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
     * and all other targets are understood as shout/whisper targets that have previously been registered via a
     * VoiceTarget message (via TCP).
     * </pre>
     *
     * <code>uint32 target = 1;</code>
     * @param value The target to set.
     */
    private void setTarget(int value) {
      headerCase_ = 1;
      header_ = value;
    }
    /**
     * <pre>
     * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
     * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
     * and all other targets are understood as shout/whisper targets that have previously been registered via a
     * VoiceTarget message (via TCP).
     * </pre>
     *
     * <code>uint32 target = 1;</code>
     */
    private void clearTarget() {
      if (headerCase_ == 1) {
        headerCase_ = 0;
        header_ = null;
      }
    }

    public static final int CONTEXT_FIELD_NUMBER = 2;
    /**
     * <pre>
     * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
     * 0: Normal speech
     * 1: Shout to channel
     * 2: Whisper to user
     * 3: Received via channel listener
     * </pre>
     *
     * <code>uint32 context = 2;</code>
     * @return Whether the context field is set.
     */
    @java.lang.Override
    public boolean hasContext() {
      return headerCase_ == 2;
    }
    /**
     * <pre>
     * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
     * 0: Normal speech
     * 1: Shout to channel
     * 2: Whisper to user
     * 3: Received via channel listener
     * </pre>
     *
     * <code>uint32 context = 2;</code>
     * @return The context.
     */
    @java.lang.Override
    public int getContext() {
      if (headerCase_ == 2) {
        return (java.lang.Integer) header_;
      }
      return 0;
    }
    /**
     * <pre>
     * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
     * 0: Normal speech
     * 1: Shout to channel
     * 2: Whisper to user
     * 3: Received via channel listener
     * </pre>
     *
     * <code>uint32 context = 2;</code>
     * @param value The context to set.
     */
    private void setContext(int value) {
      headerCase_ = 2;
      header_ = value;
    }
    /**
     * <pre>
     * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
     * 0: Normal speech
     * 1: Shout to channel
     * 2: Whisper to user
     * 3: Received via channel listener
     * </pre>
     *
     * <code>uint32 context = 2;</code>
     */
    private void clearContext() {
      if (headerCase_ == 2) {
        headerCase_ = 0;
        header_ = null;
      }
    }

    public static final int SENDER_SESSION_FIELD_NUMBER = 3;
    private int senderSession_;
    /**
     * <pre>
     * The session of the client (sender) this audio was originally sent from. This field is not required when sending
     * audio to the server, but will always be set when receiving audio from the server.
     * </pre>
     *
     * <code>uint32 sender_session = 3;</code>
     * @return The senderSession.
     */
    @java.lang.Override
    public int getSenderSession() {
      return senderSession_;
    }
    /**
     * <pre>
     * The session of the client (sender) this audio was originally sent from. This field is not required when sending
     * audio to the server, but will always be set when receiving audio from the server.
     * </pre>
     *
     * <code>uint32 sender_session = 3;</code>
     * @param value The senderSession to set.
     */
    private void setSenderSession(int value) {
      
      senderSession_ = value;
    }
    /**
     * <pre>
     * The session of the client (sender) this audio was originally sent from. This field is not required when sending
     * audio to the server, but will always be set when receiving audio from the server.
     * </pre>
     *
     * <code>uint32 sender_session = 3;</code>
     */
    private void clearSenderSession() {

      senderSession_ = 0;
    }

    public static final int FRAME_NUMBER_FIELD_NUMBER = 4;
    private long frameNumber_;
    /**
     * <pre>
     * The number of the first contained audio frame (indicating the position of that frame in the overall audio stream)
     * </pre>
     *
     * <code>uint64 frame_number = 4;</code>
     * @return The frameNumber.
     */
    @java.lang.Override
    public long getFrameNumber() {
      return frameNumber_;
    }
    /**
     * <pre>
     * The number of the first contained audio frame (indicating the position of that frame in the overall audio stream)
     * </pre>
     *
     * <code>uint64 frame_number = 4;</code>
     * @param value The frameNumber to set.
     */
    private void setFrameNumber(long value) {
      
      frameNumber_ = value;
    }
    /**
     * <pre>
     * The number of the first contained audio frame (indicating the position of that frame in the overall audio stream)
     * </pre>
     *
     * <code>uint64 frame_number = 4;</code>
     */
    private void clearFrameNumber() {

      frameNumber_ = 0L;
    }

    public static final int OPUS_DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString opusData_;
    /**
     * <pre>
     * The actual voice data payload in the Opus format.
     * </pre>
     *
     * <code>bytes opus_data = 5;</code>
     * @return The opusData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOpusData() {
      return opusData_;
    }
    /**
     * <pre>
     * The actual voice data payload in the Opus format.
     * </pre>
     *
     * <code>bytes opus_data = 5;</code>
     * @param value The opusData to set.
     */
    private void setOpusData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      opusData_ = value;
    }
    /**
     * <pre>
     * The actual voice data payload in the Opus format.
     * </pre>
     *
     * <code>bytes opus_data = 5;</code>
     */
    private void clearOpusData() {

      opusData_ = getDefaultInstance().getOpusData();
    }

    public static final int POSITIONAL_DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.FloatList positionalData_;
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @return A list containing the positionalData.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getPositionalDataList() {
      return positionalData_;
    }
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @return The count of positionalData.
     */
    @java.lang.Override
    public int getPositionalDataCount() {
      return positionalData_.size();
    }
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @param index The index of the element to return.
     * @return The positionalData at the given index.
     */
    @java.lang.Override
    public float getPositionalData(int index) {
      return positionalData_.getFloat(index);
    }
    private int positionalDataMemoizedSerializedSize = -1;
    private void ensurePositionalDataIsMutable() {
      com.google.protobuf.Internal.FloatList tmp = positionalData_;
      if (!tmp.isModifiable()) {
        positionalData_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @param index The index to set the value at.
     * @param value The positionalData to set.
     */
    private void setPositionalData(
        int index, float value) {
      ensurePositionalDataIsMutable();
      positionalData_.setFloat(index, value);
    }
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @param value The positionalData to add.
     */
    private void addPositionalData(float value) {
      ensurePositionalDataIsMutable();
      positionalData_.addFloat(value);
    }
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     * @param values The positionalData to add.
     */
    private void addAllPositionalData(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensurePositionalDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, positionalData_);
    }
    /**
     * <pre>
     * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
     * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
     * </pre>
     *
     * <code>repeated float positional_data = 6;</code>
     */
    private void clearPositionalData() {
      positionalData_ = emptyFloatList();
    }

    public static final int VOLUME_ADJUSTMENT_FIELD_NUMBER = 7;
    private float volumeAdjustment_;
    /**
     * <pre>
     * A volume adjustment determined by the server for this audio packet. It is up to the client to apply this adjustment to
     * the resulting audio (or not). Note: A value of 0 means that this field is unset.
     * </pre>
     *
     * <code>float volume_adjustment = 7;</code>
     * @return The volumeAdjustment.
     */
    @java.lang.Override
    public float getVolumeAdjustment() {
      return volumeAdjustment_;
    }
    /**
     * <pre>
     * A volume adjustment determined by the server for this audio packet. It is up to the client to apply this adjustment to
     * the resulting audio (or not). Note: A value of 0 means that this field is unset.
     * </pre>
     *
     * <code>float volume_adjustment = 7;</code>
     * @param value The volumeAdjustment to set.
     */
    private void setVolumeAdjustment(float value) {
      
      volumeAdjustment_ = value;
    }
    /**
     * <pre>
     * A volume adjustment determined by the server for this audio packet. It is up to the client to apply this adjustment to
     * the resulting audio (or not). Note: A value of 0 means that this field is unset.
     * </pre>
     *
     * <code>float volume_adjustment = 7;</code>
     */
    private void clearVolumeAdjustment() {

      volumeAdjustment_ = 0F;
    }

    public static final int IS_TERMINATOR_FIELD_NUMBER = 16;
    private boolean isTerminator_;
    /**
     * <pre>
     * A flag indicating whether this audio packet represents the end of transmission for the current audio stream
     * </pre>
     *
     * <code>bool is_terminator = 16;</code>
     * @return The isTerminator.
     */
    @java.lang.Override
    public boolean getIsTerminator() {
      return isTerminator_;
    }
    /**
     * <pre>
     * A flag indicating whether this audio packet represents the end of transmission for the current audio stream
     * </pre>
     *
     * <code>bool is_terminator = 16;</code>
     * @param value The isTerminator to set.
     */
    private void setIsTerminator(boolean value) {
      
      isTerminator_ = value;
    }
    /**
     * <pre>
     * A flag indicating whether this audio packet represents the end of transmission for the current audio stream
     * </pre>
     *
     * <code>bool is_terminator = 16;</code>
     */
    private void clearIsTerminator() {

      isTerminator_ = false;
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Audio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(se.lublin.humla.protobuf.MumbleUDP.Audio prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code MumbleUDP.Audio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          se.lublin.humla.protobuf.MumbleUDP.Audio, Builder> implements
        // @@protoc_insertion_point(builder_implements:MumbleUDP.Audio)
        se.lublin.humla.protobuf.MumbleUDP.AudioOrBuilder {
      // Construct using se.lublin.humla.protobuf.MumbleUDP.Audio.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public HeaderCase
          getHeaderCase() {
        return instance.getHeaderCase();
      }

      public Builder clearHeader() {
        copyOnWrite();
        instance.clearHeader();
        return this;
      }


      /**
       * <pre>
       * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
       * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
       * and all other targets are understood as shout/whisper targets that have previously been registered via a
       * VoiceTarget message (via TCP).
       * </pre>
       *
       * <code>uint32 target = 1;</code>
       * @return Whether the target field is set.
       */
      @java.lang.Override
      public boolean hasTarget() {
        return instance.hasTarget();
      }
      /**
       * <pre>
       * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
       * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
       * and all other targets are understood as shout/whisper targets that have previously been registered via a
       * VoiceTarget message (via TCP).
       * </pre>
       *
       * <code>uint32 target = 1;</code>
       * @return The target.
       */
      @java.lang.Override
      public int getTarget() {
        return instance.getTarget();
      }
      /**
       * <pre>
       * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
       * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
       * and all other targets are understood as shout/whisper targets that have previously been registered via a
       * VoiceTarget message (via TCP).
       * </pre>
       *
       * <code>uint32 target = 1;</code>
       * @param value The target to set.
       * @return This builder for chaining.
       */
      public Builder setTarget(int value) {
        copyOnWrite();
        instance.setTarget(value);
        return this;
      }
      /**
       * <pre>
       * When this audio is sent by the client to the server, this is set to the target of the audio data. This target
       * is a number in the range [0, 2^{32} - 1], where 0 means "normal talking", 2^{5} - 1 means "server loopback"
       * and all other targets are understood as shout/whisper targets that have previously been registered via a
       * VoiceTarget message (via TCP).
       * </pre>
       *
       * <code>uint32 target = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTarget() {
        copyOnWrite();
        instance.clearTarget();
        return this;
      }

      /**
       * <pre>
       * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
       * 0: Normal speech
       * 1: Shout to channel
       * 2: Whisper to user
       * 3: Received via channel listener
       * </pre>
       *
       * <code>uint32 context = 2;</code>
       * @return Whether the context field is set.
       */
      @java.lang.Override
      public boolean hasContext() {
        return instance.hasContext();
      }
      /**
       * <pre>
       * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
       * 0: Normal speech
       * 1: Shout to channel
       * 2: Whisper to user
       * 3: Received via channel listener
       * </pre>
       *
       * <code>uint32 context = 2;</code>
       * @return The context.
       */
      @java.lang.Override
      public int getContext() {
        return instance.getContext();
      }
      /**
       * <pre>
       * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
       * 0: Normal speech
       * 1: Shout to channel
       * 2: Whisper to user
       * 3: Received via channel listener
       * </pre>
       *
       * <code>uint32 context = 2;</code>
       * @param value The context to set.
       * @return This builder for chaining.
       */
      public Builder setContext(int value) {
        copyOnWrite();
        instance.setContext(value);
        return this;
      }
      /**
       * <pre>
       * When this audio is sent by the server to the client, this indicates the context in which the audio has been sent.
       * 0: Normal speech
       * 1: Shout to channel
       * 2: Whisper to user
       * 3: Received via channel listener
       * </pre>
       *
       * <code>uint32 context = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContext() {
        copyOnWrite();
        instance.clearContext();
        return this;
      }

      /**
       * <pre>
       * The session of the client (sender) this audio was originally sent from. This field is not required when sending
       * audio to the server, but will always be set when receiving audio from the server.
       * </pre>
       *
       * <code>uint32 sender_session = 3;</code>
       * @return The senderSession.
       */
      @java.lang.Override
      public int getSenderSession() {
        return instance.getSenderSession();
      }
      /**
       * <pre>
       * The session of the client (sender) this audio was originally sent from. This field is not required when sending
       * audio to the server, but will always be set when receiving audio from the server.
       * </pre>
       *
       * <code>uint32 sender_session = 3;</code>
       * @param value The senderSession to set.
       * @return This builder for chaining.
       */
      public Builder setSenderSession(int value) {
        copyOnWrite();
        instance.setSenderSession(value);
        return this;
      }
      /**
       * <pre>
       * The session of the client (sender) this audio was originally sent from. This field is not required when sending
       * audio to the server, but will always be set when receiving audio from the server.
       * </pre>
       *
       * <code>uint32 sender_session = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderSession() {
        copyOnWrite();
        instance.clearSenderSession();
        return this;
      }

      /**
       * <pre>
       * The number of the first contained audio frame (indicating the position of that frame in the overall audio stream)
       * </pre>
       *
       * <code>uint64 frame_number = 4;</code>
       * @return The frameNumber.
       */
      @java.lang.Override
      public long getFrameNumber() {
        return instance.getFrameNumber();
      }
      /**
       * <pre>
       * The number of the first contained audio frame (indicating the position of that frame in the overall audio stream)
       * </pre>
       *
       * <code>uint64 frame_number = 4;</code>
       * @param value The frameNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFrameNumber(long value) {
        copyOnWrite();
        instance.setFrameNumber(value);
        return this;
      }
      /**
       * <pre>
       * The number of the first contained audio frame (indicating the position of that frame in the overall audio stream)
       * </pre>
       *
       * <code>uint64 frame_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrameNumber() {
        copyOnWrite();
        instance.clearFrameNumber();
        return this;
      }

      /**
       * <pre>
       * The actual voice data payload in the Opus format.
       * </pre>
       *
       * <code>bytes opus_data = 5;</code>
       * @return The opusData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOpusData() {
        return instance.getOpusData();
      }
      /**
       * <pre>
       * The actual voice data payload in the Opus format.
       * </pre>
       *
       * <code>bytes opus_data = 5;</code>
       * @param value The opusData to set.
       * @return This builder for chaining.
       */
      public Builder setOpusData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOpusData(value);
        return this;
      }
      /**
       * <pre>
       * The actual voice data payload in the Opus format.
       * </pre>
       *
       * <code>bytes opus_data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpusData() {
        copyOnWrite();
        instance.clearOpusData();
        return this;
      }

      /**
       * <pre>
       * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
       * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
       * </pre>
       *
       * <code>repeated float positional_data = 6;</code>
       * @return A list containing the positionalData.
       */
      @java.lang.Override
      public java.util.List<java.lang.Float>
          getPositionalDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getPositionalDataList());
      }
      /**
       * <pre>
       * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
       * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
       * </pre>
       *
       * <code>repeated float positional_data = 6;</code>
       * @return The count of positionalData.
       */
      @java.lang.Override
      public int getPositionalDataCount() {
        return instance.getPositionalDataCount();
      }
      /**
       * <pre>
       * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
       * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
       * </pre>
       *
       * <code>repeated float positional_data = 6;</code>
       * @param index The index of the element to return.
       * @return The positionalData at the given index.
       */
      @java.lang.Override
      public float getPositionalData(int index) {
        return instance.getPositionalData(index);
      }
      /**
       * <pre>
       * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
       * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
       * </pre>
       *
       * <code>repeated float positional_data = 6;</code>
       * @param value The positionalData to set.
       * @return This builder for chaining.
       */
      public Builder setPositionalData(
          int index, float value) {
        copyOnWrite();
        instance.setPositionalData(index, value);
        return this;
      }
      /**
       * <pre>
       * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
       * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
       * </pre>
       *
       * <code>repeated float positional_data = 6;</code>
       * @param value The positionalData to add.
       * @return This builder for chaining.
       */
      public Builder addPositionalData(float value) {
        copyOnWrite();
        instance.addPositionalData(value);
        return this;
      }
      /**
       * <pre>
       * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
       * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
       * </pre>
       *
       * <code>repeated float positional_data = 6;</code>
       * @param values The positionalData to add.
       * @return This builder for chaining.
       */
      public Builder addAllPositionalData(
          java.lang.Iterable<? extends java.lang.Float> values) {
        copyOnWrite();
        instance.addAllPositionalData(values);
        return this;
      }
      /**
       * <pre>
       * Optional positional data indicating the speaker's position in a virtual world (in meters). This "list" is really
       * expected to be an array of size 3 containing the X, Y and Z coordinates of the position (in that order).
       * </pre>
       *
       * <code>repeated float positional_data = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPositionalData() {
        copyOnWrite();
        instance.clearPositionalData();
        return this;
      }

      /**
       * <pre>
       * A volume adjustment determined by the server for this audio packet. It is up to the client to apply this adjustment to
       * the resulting audio (or not). Note: A value of 0 means that this field is unset.
       * </pre>
       *
       * <code>float volume_adjustment = 7;</code>
       * @return The volumeAdjustment.
       */
      @java.lang.Override
      public float getVolumeAdjustment() {
        return instance.getVolumeAdjustment();
      }
      /**
       * <pre>
       * A volume adjustment determined by the server for this audio packet. It is up to the client to apply this adjustment to
       * the resulting audio (or not). Note: A value of 0 means that this field is unset.
       * </pre>
       *
       * <code>float volume_adjustment = 7;</code>
       * @param value The volumeAdjustment to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeAdjustment(float value) {
        copyOnWrite();
        instance.setVolumeAdjustment(value);
        return this;
      }
      /**
       * <pre>
       * A volume adjustment determined by the server for this audio packet. It is up to the client to apply this adjustment to
       * the resulting audio (or not). Note: A value of 0 means that this field is unset.
       * </pre>
       *
       * <code>float volume_adjustment = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeAdjustment() {
        copyOnWrite();
        instance.clearVolumeAdjustment();
        return this;
      }

      /**
       * <pre>
       * A flag indicating whether this audio packet represents the end of transmission for the current audio stream
       * </pre>
       *
       * <code>bool is_terminator = 16;</code>
       * @return The isTerminator.
       */
      @java.lang.Override
      public boolean getIsTerminator() {
        return instance.getIsTerminator();
      }
      /**
       * <pre>
       * A flag indicating whether this audio packet represents the end of transmission for the current audio stream
       * </pre>
       *
       * <code>bool is_terminator = 16;</code>
       * @param value The isTerminator to set.
       * @return This builder for chaining.
       */
      public Builder setIsTerminator(boolean value) {
        copyOnWrite();
        instance.setIsTerminator(value);
        return this;
      }
      /**
       * <pre>
       * A flag indicating whether this audio packet represents the end of transmission for the current audio stream
       * </pre>
       *
       * <code>bool is_terminator = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsTerminator() {
        copyOnWrite();
        instance.clearIsTerminator();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MumbleUDP.Audio)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new se.lublin.humla.protobuf.MumbleUDP.Audio();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "header_",
              "headerCase_",
              "senderSession_",
              "frameNumber_",
              "opusData_",
              "positionalData_",
              "volumeAdjustment_",
              "isTerminator_",
            };
            java.lang.String info =
                "\u0000\b\u0001\u0000\u0001\u0010\b\u0000\u0001\u0000\u0001>\u0000\u0002>\u0000\u0003" +
                "\u000b\u0004\u0003\u0005\n\u0006$\u0007\u0001\u0010\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<se.lublin.humla.protobuf.MumbleUDP.Audio> parser = PARSER;
          if (parser == null) {
            synchronized (se.lublin.humla.protobuf.MumbleUDP.Audio.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<se.lublin.humla.protobuf.MumbleUDP.Audio>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:MumbleUDP.Audio)
    private static final se.lublin.humla.protobuf.MumbleUDP.Audio DEFAULT_INSTANCE;
    static {
      Audio defaultInstance = new Audio();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Audio.class, defaultInstance);
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Audio getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Audio> PARSER;

    public static com.google.protobuf.Parser<Audio> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MumbleUDP.Ping)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Timestamp as encoded by the client. A server is not supposed to attempt to decode or modify this field. Therefore,
     * clients may choose an arbitrary format for this timestamp (as long as it fits into a uint64 field).
     * </pre>
     *
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * A flag set by the sending client, if it wants to obtain additional information about the server.
     * </pre>
     *
     * <code>bool request_extended_information = 2;</code>
     * @return The requestExtendedInformation.
     */
    boolean getRequestExtendedInformation();

    /**
     * <pre>
     * The version of the server in the new version format.
     * The new protobuf Ping packet introduced with 1.5 drops support for the legacy version format
     * since both server and client have to support this new format.
     * (See https://github.com/mumble-voip/mumble/issues/5827)
     * </pre>
     *
     * <code>uint64 server_version_v2 = 3;</code>
     * @return The serverVersionV2.
     */
    long getServerVersionV2();

    /**
     * <pre>
     * The amount of users currently connected to the server
     * </pre>
     *
     * <code>uint32 user_count = 4;</code>
     * @return The userCount.
     */
    int getUserCount();

    /**
     * <pre>
     * The maximum amount of users permitted on this server
     * </pre>
     *
     * <code>uint32 max_user_count = 5;</code>
     * @return The maxUserCount.
     */
    int getMaxUserCount();

    /**
     * <pre>
     * The maximum bandwidth each user is allowed to use for sending audio to the server
     * </pre>
     *
     * <code>uint32 max_bandwidth_per_user = 6;</code>
     * @return The maxBandwidthPerUser.
     */
    int getMaxBandwidthPerUser();
  }
  /**
   * <pre>
   * *
   * Ping message for checking UDP connectivity (and roundtrip ping) and potentially obtaining further server
   * details (e.g. version).
   * </pre>
   *
   * Protobuf type {@code MumbleUDP.Ping}
   */
  public  static final class Ping extends
      com.google.protobuf.GeneratedMessageLite<
          Ping, Ping.Builder> implements
      // @@protoc_insertion_point(message_implements:MumbleUDP.Ping)
      PingOrBuilder {
    private Ping() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <pre>
     * Timestamp as encoded by the client. A server is not supposed to attempt to decode or modify this field. Therefore,
     * clients may choose an arbitrary format for this timestamp (as long as it fits into a uint64 field).
     * </pre>
     *
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Timestamp as encoded by the client. A server is not supposed to attempt to decode or modify this field. Therefore,
     * clients may choose an arbitrary format for this timestamp (as long as it fits into a uint64 field).
     * </pre>
     *
     * <code>uint64 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * Timestamp as encoded by the client. A server is not supposed to attempt to decode or modify this field. Therefore,
     * clients may choose an arbitrary format for this timestamp (as long as it fits into a uint64 field).
     * </pre>
     *
     * <code>uint64 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0L;
    }

    public static final int REQUEST_EXTENDED_INFORMATION_FIELD_NUMBER = 2;
    private boolean requestExtendedInformation_;
    /**
     * <pre>
     * A flag set by the sending client, if it wants to obtain additional information about the server.
     * </pre>
     *
     * <code>bool request_extended_information = 2;</code>
     * @return The requestExtendedInformation.
     */
    @java.lang.Override
    public boolean getRequestExtendedInformation() {
      return requestExtendedInformation_;
    }
    /**
     * <pre>
     * A flag set by the sending client, if it wants to obtain additional information about the server.
     * </pre>
     *
     * <code>bool request_extended_information = 2;</code>
     * @param value The requestExtendedInformation to set.
     */
    private void setRequestExtendedInformation(boolean value) {
      
      requestExtendedInformation_ = value;
    }
    /**
     * <pre>
     * A flag set by the sending client, if it wants to obtain additional information about the server.
     * </pre>
     *
     * <code>bool request_extended_information = 2;</code>
     */
    private void clearRequestExtendedInformation() {

      requestExtendedInformation_ = false;
    }

    public static final int SERVER_VERSION_V2_FIELD_NUMBER = 3;
    private long serverVersionV2_;
    /**
     * <pre>
     * The version of the server in the new version format.
     * The new protobuf Ping packet introduced with 1.5 drops support for the legacy version format
     * since both server and client have to support this new format.
     * (See https://github.com/mumble-voip/mumble/issues/5827)
     * </pre>
     *
     * <code>uint64 server_version_v2 = 3;</code>
     * @return The serverVersionV2.
     */
    @java.lang.Override
    public long getServerVersionV2() {
      return serverVersionV2_;
    }
    /**
     * <pre>
     * The version of the server in the new version format.
     * The new protobuf Ping packet introduced with 1.5 drops support for the legacy version format
     * since both server and client have to support this new format.
     * (See https://github.com/mumble-voip/mumble/issues/5827)
     * </pre>
     *
     * <code>uint64 server_version_v2 = 3;</code>
     * @param value The serverVersionV2 to set.
     */
    private void setServerVersionV2(long value) {
      
      serverVersionV2_ = value;
    }
    /**
     * <pre>
     * The version of the server in the new version format.
     * The new protobuf Ping packet introduced with 1.5 drops support for the legacy version format
     * since both server and client have to support this new format.
     * (See https://github.com/mumble-voip/mumble/issues/5827)
     * </pre>
     *
     * <code>uint64 server_version_v2 = 3;</code>
     */
    private void clearServerVersionV2() {

      serverVersionV2_ = 0L;
    }

    public static final int USER_COUNT_FIELD_NUMBER = 4;
    private int userCount_;
    /**
     * <pre>
     * The amount of users currently connected to the server
     * </pre>
     *
     * <code>uint32 user_count = 4;</code>
     * @return The userCount.
     */
    @java.lang.Override
    public int getUserCount() {
      return userCount_;
    }
    /**
     * <pre>
     * The amount of users currently connected to the server
     * </pre>
     *
     * <code>uint32 user_count = 4;</code>
     * @param value The userCount to set.
     */
    private void setUserCount(int value) {
      
      userCount_ = value;
    }
    /**
     * <pre>
     * The amount of users currently connected to the server
     * </pre>
     *
     * <code>uint32 user_count = 4;</code>
     */
    private void clearUserCount() {

      userCount_ = 0;
    }

    public static final int MAX_USER_COUNT_FIELD_NUMBER = 5;
    private int maxUserCount_;
    /**
     * <pre>
     * The maximum amount of users permitted on this server
     * </pre>
     *
     * <code>uint32 max_user_count = 5;</code>
     * @return The maxUserCount.
     */
    @java.lang.Override
    public int getMaxUserCount() {
      return maxUserCount_;
    }
    /**
     * <pre>
     * The maximum amount of users permitted on this server
     * </pre>
     *
     * <code>uint32 max_user_count = 5;</code>
     * @param value The maxUserCount to set.
     */
    private void setMaxUserCount(int value) {
      
      maxUserCount_ = value;
    }
    /**
     * <pre>
     * The maximum amount of users permitted on this server
     * </pre>
     *
     * <code>uint32 max_user_count = 5;</code>
     */
    private void clearMaxUserCount() {

      maxUserCount_ = 0;
    }

    public static final int MAX_BANDWIDTH_PER_USER_FIELD_NUMBER = 6;
    private int maxBandwidthPerUser_;
    /**
     * <pre>
     * The maximum bandwidth each user is allowed to use for sending audio to the server
     * </pre>
     *
     * <code>uint32 max_bandwidth_per_user = 6;</code>
     * @return The maxBandwidthPerUser.
     */
    @java.lang.Override
    public int getMaxBandwidthPerUser() {
      return maxBandwidthPerUser_;
    }
    /**
     * <pre>
     * The maximum bandwidth each user is allowed to use for sending audio to the server
     * </pre>
     *
     * <code>uint32 max_bandwidth_per_user = 6;</code>
     * @param value The maxBandwidthPerUser to set.
     */
    private void setMaxBandwidthPerUser(int value) {
      
      maxBandwidthPerUser_ = value;
    }
    /**
     * <pre>
     * The maximum bandwidth each user is allowed to use for sending audio to the server
     * </pre>
     *
     * <code>uint32 max_bandwidth_per_user = 6;</code>
     */
    private void clearMaxBandwidthPerUser() {

      maxBandwidthPerUser_ = 0;
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.lublin.humla.protobuf.MumbleUDP.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(se.lublin.humla.protobuf.MumbleUDP.Ping prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * *
     * Ping message for checking UDP connectivity (and roundtrip ping) and potentially obtaining further server
     * details (e.g. version).
     * </pre>
     *
     * Protobuf type {@code MumbleUDP.Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          se.lublin.humla.protobuf.MumbleUDP.Ping, Builder> implements
        // @@protoc_insertion_point(builder_implements:MumbleUDP.Ping)
        se.lublin.humla.protobuf.MumbleUDP.PingOrBuilder {
      // Construct using se.lublin.humla.protobuf.MumbleUDP.Ping.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Timestamp as encoded by the client. A server is not supposed to attempt to decode or modify this field. Therefore,
       * clients may choose an arbitrary format for this timestamp (as long as it fits into a uint64 field).
       * </pre>
       *
       * <code>uint64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * Timestamp as encoded by the client. A server is not supposed to attempt to decode or modify this field. Therefore,
       * clients may choose an arbitrary format for this timestamp (as long as it fits into a uint64 field).
       * </pre>
       *
       * <code>uint64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * Timestamp as encoded by the client. A server is not supposed to attempt to decode or modify this field. Therefore,
       * clients may choose an arbitrary format for this timestamp (as long as it fits into a uint64 field).
       * </pre>
       *
       * <code>uint64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * A flag set by the sending client, if it wants to obtain additional information about the server.
       * </pre>
       *
       * <code>bool request_extended_information = 2;</code>
       * @return The requestExtendedInformation.
       */
      @java.lang.Override
      public boolean getRequestExtendedInformation() {
        return instance.getRequestExtendedInformation();
      }
      /**
       * <pre>
       * A flag set by the sending client, if it wants to obtain additional information about the server.
       * </pre>
       *
       * <code>bool request_extended_information = 2;</code>
       * @param value The requestExtendedInformation to set.
       * @return This builder for chaining.
       */
      public Builder setRequestExtendedInformation(boolean value) {
        copyOnWrite();
        instance.setRequestExtendedInformation(value);
        return this;
      }
      /**
       * <pre>
       * A flag set by the sending client, if it wants to obtain additional information about the server.
       * </pre>
       *
       * <code>bool request_extended_information = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestExtendedInformation() {
        copyOnWrite();
        instance.clearRequestExtendedInformation();
        return this;
      }

      /**
       * <pre>
       * The version of the server in the new version format.
       * The new protobuf Ping packet introduced with 1.5 drops support for the legacy version format
       * since both server and client have to support this new format.
       * (See https://github.com/mumble-voip/mumble/issues/5827)
       * </pre>
       *
       * <code>uint64 server_version_v2 = 3;</code>
       * @return The serverVersionV2.
       */
      @java.lang.Override
      public long getServerVersionV2() {
        return instance.getServerVersionV2();
      }
      /**
       * <pre>
       * The version of the server in the new version format.
       * The new protobuf Ping packet introduced with 1.5 drops support for the legacy version format
       * since both server and client have to support this new format.
       * (See https://github.com/mumble-voip/mumble/issues/5827)
       * </pre>
       *
       * <code>uint64 server_version_v2 = 3;</code>
       * @param value The serverVersionV2 to set.
       * @return This builder for chaining.
       */
      public Builder setServerVersionV2(long value) {
        copyOnWrite();
        instance.setServerVersionV2(value);
        return this;
      }
      /**
       * <pre>
       * The version of the server in the new version format.
       * The new protobuf Ping packet introduced with 1.5 drops support for the legacy version format
       * since both server and client have to support this new format.
       * (See https://github.com/mumble-voip/mumble/issues/5827)
       * </pre>
       *
       * <code>uint64 server_version_v2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerVersionV2() {
        copyOnWrite();
        instance.clearServerVersionV2();
        return this;
      }

      /**
       * <pre>
       * The amount of users currently connected to the server
       * </pre>
       *
       * <code>uint32 user_count = 4;</code>
       * @return The userCount.
       */
      @java.lang.Override
      public int getUserCount() {
        return instance.getUserCount();
      }
      /**
       * <pre>
       * The amount of users currently connected to the server
       * </pre>
       *
       * <code>uint32 user_count = 4;</code>
       * @param value The userCount to set.
       * @return This builder for chaining.
       */
      public Builder setUserCount(int value) {
        copyOnWrite();
        instance.setUserCount(value);
        return this;
      }
      /**
       * <pre>
       * The amount of users currently connected to the server
       * </pre>
       *
       * <code>uint32 user_count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserCount() {
        copyOnWrite();
        instance.clearUserCount();
        return this;
      }

      /**
       * <pre>
       * The maximum amount of users permitted on this server
       * </pre>
       *
       * <code>uint32 max_user_count = 5;</code>
       * @return The maxUserCount.
       */
      @java.lang.Override
      public int getMaxUserCount() {
        return instance.getMaxUserCount();
      }
      /**
       * <pre>
       * The maximum amount of users permitted on this server
       * </pre>
       *
       * <code>uint32 max_user_count = 5;</code>
       * @param value The maxUserCount to set.
       * @return This builder for chaining.
       */
      public Builder setMaxUserCount(int value) {
        copyOnWrite();
        instance.setMaxUserCount(value);
        return this;
      }
      /**
       * <pre>
       * The maximum amount of users permitted on this server
       * </pre>
       *
       * <code>uint32 max_user_count = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxUserCount() {
        copyOnWrite();
        instance.clearMaxUserCount();
        return this;
      }

      /**
       * <pre>
       * The maximum bandwidth each user is allowed to use for sending audio to the server
       * </pre>
       *
       * <code>uint32 max_bandwidth_per_user = 6;</code>
       * @return The maxBandwidthPerUser.
       */
      @java.lang.Override
      public int getMaxBandwidthPerUser() {
        return instance.getMaxBandwidthPerUser();
      }
      /**
       * <pre>
       * The maximum bandwidth each user is allowed to use for sending audio to the server
       * </pre>
       *
       * <code>uint32 max_bandwidth_per_user = 6;</code>
       * @param value The maxBandwidthPerUser to set.
       * @return This builder for chaining.
       */
      public Builder setMaxBandwidthPerUser(int value) {
        copyOnWrite();
        instance.setMaxBandwidthPerUser(value);
        return this;
      }
      /**
       * <pre>
       * The maximum bandwidth each user is allowed to use for sending audio to the server
       * </pre>
       *
       * <code>uint32 max_bandwidth_per_user = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxBandwidthPerUser() {
        copyOnWrite();
        instance.clearMaxBandwidthPerUser();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MumbleUDP.Ping)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new se.lublin.humla.protobuf.MumbleUDP.Ping();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
              "requestExtendedInformation_",
              "serverVersionV2_",
              "userCount_",
              "maxUserCount_",
              "maxBandwidthPerUser_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0003\u0002\u0007" +
                "\u0003\u0003\u0004\u000b\u0005\u000b\u0006\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<se.lublin.humla.protobuf.MumbleUDP.Ping> parser = PARSER;
          if (parser == null) {
            synchronized (se.lublin.humla.protobuf.MumbleUDP.Ping.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<se.lublin.humla.protobuf.MumbleUDP.Ping>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:MumbleUDP.Ping)
    private static final se.lublin.humla.protobuf.MumbleUDP.Ping DEFAULT_INSTANCE;
    static {
      Ping defaultInstance = new Ping();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Ping.class, defaultInstance);
    }

    public static se.lublin.humla.protobuf.MumbleUDP.Ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Ping> PARSER;

    public static com.google.protobuf.Parser<Ping> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
